[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "ammo"
version = "0.1"
description = "A simple terminal based mod organizer for Linux."
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "cyberrumor" }]

[project.urls]
Homepage = "https://github.com/cyberrumor/ammo"

[project.optional-dependencies]
test = [
    "pytest==9.1.1",
    "pytest-cov==7.1.0",
    "setuptools==83.0.0",
]

[tool.setuptools]
packages = ["ammo", "ammo.controller"]
script-files = ["ammo/bin/ammo"]
include-package-data = false
