name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install mise
      uses: jdx/mise-action@v2

    - name: Lint
      run: ruff check --output-format=github

    - name: Format
      run: ruff format --diff

    - name: Test
      run: uv run --extra test pytest --cov=.

    - name: Install ammo with pipx
      run: pipx install .
