# This workflow will install Python dependencies and run tests.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.9"
    - name: Install dependencies
      run: |
        python3 -m venv .venv
        . .venv/bin/activate
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Install ammo
      run: |
        . .venv/bin/activate
        pip install --break-system-packages --force-reinstall .
    - name: Test with pytest
      run: |
        . .venv/bin/activate
        pytest -v
